### ISSUE TITLE
any plans to support for Ubuntu 14.04, 16.04 ?

### ISSUE THREAD

**Issue by lhoss** [mongrelion/ansible-role-docker#3]
Officially (infos from meta.yml) your role does not support Ubuntu.
I'm interested as I soon need to support both debian/ubuntu and redhat/centos worlds with proper docker deployments.

Usually not many changes required to extend debian with ubuntu support.
Ideally we could merge (the quite advanced) functionality from https://github.com/angstwad/docker.ubuntu (which is ubuntu only though).

Or can anyone propose another popular role?
A galaxy query: https://galaxy.ansible.com/list#/roles?page=1&page_size=10&tags=ubuntu&autocomplete=docker%20redhat
only found: https://github.com/abaez/ansible-role-docker
which install using `pip` and the official docker install script (instead of `apt` resp. `yum` )

ps: Galaxy infos seem outdated, and only list EL-7 support: https://galaxy.ansible.com/mongrelion/docker/

**Comment by mongrelion** [comment]
Hey, @lhoss, thanks for the heads up. It seems like the TravisCI integration has been dead for a while and so Ansible Galaxy was not being notified on the latest updates of this repository.
I have manually triggered a build on Travis and now I can see that the meta data of the galaxy role has been updated.

Regarding Ubuntu, I hadn't really thought about it but it makes sense to add support for it since it's a big player in the server world.
I'm quite busy this week but I'm willing to give it a try the next one, unless there's a volunteer that can take care of it.

@brucellino ? :)

**Comment by brucellino** [comment]
Hey @mongrelion Ja, I could try test on Ubuntu. Would like to give you an eta, but I'm a bit busy in a hackfest in Lagos at the moment. Can we set a remind-date on this for 2 weeks ?

**Comment by mongrelion** [comment]
@brucellino kief! no problem. Take it easy and have fun.
If I get some time the next week, though, I'll give it a try.
Let's keep all the convo here.

**Comment by mongrelion** [comment]
@lhoss I just realised that Ubuntu 12.04 does not come with `systemd`. This makes it really difficult to keep a uniform installation way across the different distros.
The good news is that Ubuntu Xenial *does* come with `systemd`, so I added support for that. Could you please test that out in your system(s) and let me know if is working accordingly?

**Comment by lhoss** [comment]
@mongrelion cool you added some Ubuntu support !
I'ld say not many people still need Ubuntu 12.04, but I guess you meant 14.04?! (in which you can install systemd, but not used by default)   
About Ubuntu 16.04 I can't yet really use, sorry. But once we switch (or have as setup with redhat) I will for sure start using your role!

ps: Just quickly had a look to the systemd template, and don't really grasp how it should load docker?
Also what is consul doing there ?! 
(I don't mind any consul integration, but should be configurable ..as I guess most people don't use consul ;)
https://github.com/mongrelion/ansible-role-docker/blob/master/templates/daemon.j2.json

I'ld expect more a template like: https://github.com/angstwad/docker.ubuntu/blob/master/templates/docker.conf

**Comment by mongrelion** [comment]
@lhoss sorry, yes, I meant 14.04 😞 

Indeed, you can install systemd on your old Ubuntu installation but I can't see people doing that in their production environments just like that, hence me not wanting to add support for it.

As for Consul, it's required if you want to enable Docker's support for overlay networks. As you can see in the template file, this option will be enabled only if the `docker_clusterstore` variable is set to true, which by default is set to false https://github.com/mongrelion/ansible-role-docker/blob/master/defaults/main.yml#L3

I need to update the documentation because it is, indeed, confusing 👍 

This is how systemd will run docker: https://github.com/mongrelion/ansible-role-docker/blob/master/files/docker.service#L11

**Comment by mongrelion** [comment]
I'm closing up this issue since support for Ubuntu 16.04 has been added and support for Ubuntu 14.04 is (I think) not going to be added any time soon.

If anyone wants to submit a pull request for it, please feel free to do so.

Cheers.
