### ISSUE TITLE
Clarify supported Docker versions

### ISSUE THREAD

**Issue by marcusianlevine** [mongrelion/ansible-role-docker#46]
I tried to run my existing playbooks with the latest version and got an error when trying to install with `docker_version: 17.06` on Ubuntu 16.04 because the specified version is not available from the configured apt repo.

So it seems we no longer support all of the versions of the Docker engine we used to with the old 0.1.0 Rancher scripts.

The new logic relies on the yum/apt repositories at [https://download.docker.com/linux/](https://download.docker.com/linux/{) but these repos seem to only support edge, nightly, test and stable tags — not individual Docker versions. 

For now I just pinned down to 0.1.0, but we should clarify in the README which versions of Docker can be installed with this role, and ideally provide options for people to install older versions of the Docker engine, maybe just falling back to the Rancher scripts if need be...

**Comment by paulfantom** [comment]
Those repos have previous docker versions in them, so there is no need of reverting to rancher script. For example full version of docker 17.06 on ubuntu 16.04 is `17.06.0~ce-0~ubuntu`.

I think that there is a problem how `docker_package` variable is created and that's why setting `docker_version: 17.06` failed on ubuntu. Probably setting `docker_version: 17.06.0~ce-0~ubuntu` would temporarily solve this, could you test it?

**Comment by mongrelion** [comment]
Is it possible to reproduce this issue in our current test suite? If so, I'd like to see it attached to whatever proposal for a fix to make sure that it is truly fixed.

**Comment by paulfantom** [comment]
We would need another test scenario, and molecule 1.x doesn't support multiple scenarios. Right now it's either `latest` or some specified version.

**Comment by paulfantom** [comment]
@mongrelion I did a migration to molecule 2.x in #49, after merging it I can rebase #47 and add there another scenario with more tests including one with pinned docker version.
