### ISSUE TITLE
docker_storagedriver is not expanded correctly

### ISSUE THREAD

**Issue by frankschmitt** [mongrelion/ansible-role-docker#7]
Unfortunately, commit 18c999731ef48089e516e7adfc4b89ca8dcc29b3 seems to have broken the setup; when I try to apply this cookbook, I get

```
RUNNING HANDLER [mongrelion.docker : restart docker] ***************************
fatal: [ansible-host]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to start service docker: Job for docker.service failed because the control process exited with error code. See \"systemctl status docker.service\" and \"journalctl -xe\" for details.\n"}
```
Apparently, this happens because docker_storagedriver doesn't get expanded:

```
[centos@ansible-target tmp]$ systemctl status docker.service -l
 docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2017-02-08 14:55:52 UTC; 5min ago
     Docs: https://docs.docker.com
  Process: 23845 ExecStart=/usr/bin/docker daemon -H unix:///var/run/docker.sock -s {{ docker_storagedriver }} (code=exited, status=1/FAILURE)
```

(I'm just getting started with Ansible, so I'm not sure what exactly the root cause is - perhaps a missing $ in front of docker_storagedriver in files/docker.service ? )

**Comment by mongrelion** [comment]
Hello, @frankschmitt 

Thanks for reporting this bug.

The problem is that we're using the `copy` module to upload the systemd unit file to the server, which does not interpolate/expands any variables. Instead we should use the `template` module, which does indeed interpolate/expands variables before uploading files to the server.

I have already submitted a patch. Could you please check that out, see if the problem is fixed? Then I can close this issue.

**Comment by frankschmitt** [comment]
Hi @mongrelion ,

the problem is fixed, thanks a lot!
